# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordname', models.CharField(max_length=6)),
            ],
        ),
    ]
