# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_header',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
