# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0002_record_record_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_header',
        ),
        migrations.AddField(
            model_name='record',
            name='record_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
