# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0003_auto_20171114_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_image',
            field=models.FileField(upload_to=''),
        ),
    ]
