# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0004_auto_20171114_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_image',
            field=models.CharField(max_length=6),
        ),
    ]
